from pygame import USEREVENT

WIN_EVENT = USEREVENT + 1
SPAWN_WAVE_EVENT = USEREVENT + 2
# probably not necessary:
# PLAYER_HIT_EVENT = USEREVENT + 3
# PLAYER_HEALTH_CRITICAL_EVENT = USEREVENT + 4
PLAYER_KILLED_EVENT = USEREVENT + 5
ENEMY_KILLED_EVENT = USEREVENT + 6
ENEMY_DESPAWN_EVENT = USEREVENT + 7
